# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choix_cado', '0002_remove_user_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='default', max_length=100, verbose_name='Mot de passe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
    ]
